borreguiles: {top: 0.93, left: 0.93, bottom: 0.99, right: 0.995}
stadium:     {top: 0.93, left: 0.93, bottom: 0.99, right: 0.995}
satelite:    {top: 0.93, left: 0.93, bottom: 0.99, right: 0.995}
veleta:      {top: 0.93, left: 0.93, bottom: 0.99, right: 0.995}
