borreguiles: {top: 0.86, left: 0.78, bottom: 0.98, right: 0.98}
stadium:     {top: 0.86, left: 0.78, bottom: 0.98, right: 0.98}
satelite:    {top: 0.86, left: 0.78, bottom: 0.98, right: 0.98}
veleta:      {top: 0.86, left: 0.78, bottom: 0.98, right: 0.98}
